# Generated by Django 5.0 on 2025-01-25 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=10)),
                ('class_field', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('selection', models.CharField(max_length=40)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.student')),
            ],
        ),
    ]
